spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://175.24.98.48:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123123

  jpa:
    hibernate:
      ddl-auto: noe
    show-sql: true

logging:
  level:
    root: warn
    com.myproject.myblog: info
  file: log/blog-pro.log
#指定生产环境端口号8081，开发环境默认是8080
server:
  port: 8081